-- QuickTicket 초기 스키마: 이벤트 / 좌석

create table events (
    id           bigint generated by default as identity primary key,
    event_nm     varchar(255) not null,
    open_dt      timestamp    not null,
    total_quota  integer      not null,
    issued_count integer      not null default 0,
    valid_from   date,
    valid_to     date,
    status       varchar(20)  not null,
    close_reason varchar(255),
    closed_at    timestamp,
    created_at   timestamp    not null default now(),
    updated_at   timestamp    not null default now()
);

create table seats (
    id       bigint generated by default as identity primary key,
    event_id bigint      not null,
    seat_no  varchar(10) not null,
    grade    varchar(10) not null,
    status   varchar(20) not null,
    constraint fk_seats_event foreign key (event_id) references events (id),
    constraint uk_seats_event_seat_no unique (event_id, seat_no)
);

-- 좌석 현황 조회(상태 필터) 및 이벤트별 좌석 조회 대비
create index idx_seats_event_status on seats (event_id, status);
